BASE_LOG_DIR="/home/andrewor/local/logs/unsloth"

export QUANTIZATION_SCHEME="int4"
export FULL_FINETUNING="false"
export GRADIENT_ACCUMULATION_STEPS=1

#export MODEL="Gemma3-12B"
#export BATCH_SIZE=16
#CUDA_VISIBLE_DEVICES=0 LEARNING_RATE=2e-4 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="true" ./super_run_unsloth.sh &
#CUDA_VISIBLE_DEVICES=1 LEARNING_RATE=2e-4 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="false" ./super_run_unsloth.sh &
#CUDA_VISIBLE_DEVICES=2 LEARNING_RATE=1e-4 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="true" ./super_run_unsloth.sh &
#CUDA_VISIBLE_DEVICES=3 LEARNING_RATE=1e-4 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="false" ./super_run_unsloth.sh &
#wait
#CUDA_VISIBLE_DEVICES=0 LEARNING_RATE=4e-5 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="true" ./super_run_unsloth.sh &
#CUDA_VISIBLE_DEVICES=1 LEARNING_RATE=4e-5 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="false" ./super_run_unsloth.sh &
#CUDA_VISIBLE_DEVICES=2 LEARNING_RATE=2e-5 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="true" ./super_run_unsloth.sh &
#CUDA_VISIBLE_DEVICES=3 LEARNING_RATE=2e-5 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="false" ./super_run_unsloth.sh &
#wait
#
#export MODEL="Gemma3-4B"
#export BATCH_SIZE=32
#CUDA_VISIBLE_DEVICES=0 LEARNING_RATE=2e-4 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="true" ./super_run_unsloth.sh &
#CUDA_VISIBLE_DEVICES=1 LEARNING_RATE=2e-4 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="false" ./super_run_unsloth.sh &
#CUDA_VISIBLE_DEVICES=2 LEARNING_RATE=1e-4 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="true" ./super_run_unsloth.sh &
#CUDA_VISIBLE_DEVICES=3 LEARNING_RATE=1e-4 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="false" ./super_run_unsloth.sh &
#wait
#CUDA_VISIBLE_DEVICES=0 LEARNING_RATE=4e-5 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="true" ./super_run_unsloth.sh &
#CUDA_VISIBLE_DEVICES=1 LEARNING_RATE=4e-5 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="false" ./super_run_unsloth.sh &
#CUDA_VISIBLE_DEVICES=2 LEARNING_RATE=2e-5 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="true" ./super_run_unsloth.sh &
#CUDA_VISIBLE_DEVICES=3 LEARNING_RATE=2e-5 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="false" ./super_run_unsloth.sh &
#wait

export MODEL="Qwen3-8B"
export BATCH_SIZE=16
CUDA_VISIBLE_DEVICES=0 LEARNING_RATE=2e-4 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="true" ./super_run_unsloth.sh &
CUDA_VISIBLE_DEVICES=1 LEARNING_RATE=2e-4 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="false" ./super_run_unsloth.sh &
CUDA_VISIBLE_DEVICES=2 LEARNING_RATE=1e-4 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="true" ./super_run_unsloth.sh &
CUDA_VISIBLE_DEVICES=3 LEARNING_RATE=1e-4 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="false" ./super_run_unsloth.sh &
wait
CUDA_VISIBLE_DEVICES=0 LEARNING_RATE=4e-5 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="true" ./super_run_unsloth.sh &
CUDA_VISIBLE_DEVICES=1 LEARNING_RATE=4e-5 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="false" ./super_run_unsloth.sh &
CUDA_VISIBLE_DEVICES=2 LEARNING_RATE=2e-5 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="true" ./super_run_unsloth.sh &
CUDA_VISIBLE_DEVICES=3 LEARNING_RATE=2e-5 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="false" ./super_run_unsloth.sh &
wait

export MODEL="Qwen3-4B-Instruct"
export BATCH_SIZE=32
CUDA_VISIBLE_DEVICES=0 LEARNING_RATE=2e-4 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="true" ./super_run_unsloth.sh &
CUDA_VISIBLE_DEVICES=1 LEARNING_RATE=2e-4 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="false" ./super_run_unsloth.sh &
CUDA_VISIBLE_DEVICES=2 LEARNING_RATE=1e-4 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="true" ./super_run_unsloth.sh &
CUDA_VISIBLE_DEVICES=3 LEARNING_RATE=1e-4 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="false" ./super_run_unsloth.sh &
wait
CUDA_VISIBLE_DEVICES=0 LEARNING_RATE=4e-5 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="true" ./super_run_unsloth.sh &
CUDA_VISIBLE_DEVICES=1 LEARNING_RATE=4e-5 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="false" ./super_run_unsloth.sh &
CUDA_VISIBLE_DEVICES=2 LEARNING_RATE=2e-5 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="true" ./super_run_unsloth.sh &
CUDA_VISIBLE_DEVICES=3 LEARNING_RATE=2e-5 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="false" ./super_run_unsloth.sh &
wait

export MODEL="Llama3.2-3B"
export BATCH_SIZE=64
CUDA_VISIBLE_DEVICES=0 LEARNING_RATE=2e-4 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="true" ./super_run_unsloth.sh &
CUDA_VISIBLE_DEVICES=1 LEARNING_RATE=2e-4 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="false" ./super_run_unsloth.sh &
CUDA_VISIBLE_DEVICES=2 LEARNING_RATE=1e-4 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="true" ./super_run_unsloth.sh &
CUDA_VISIBLE_DEVICES=3 LEARNING_RATE=1e-4 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="false" ./super_run_unsloth.sh &
wait
CUDA_VISIBLE_DEVICES=0 LEARNING_RATE=4e-5 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="true" ./super_run_unsloth.sh &
CUDA_VISIBLE_DEVICES=1 LEARNING_RATE=4e-5 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="false" ./super_run_unsloth.sh &
CUDA_VISIBLE_DEVICES=2 LEARNING_RATE=2e-5 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="true" ./super_run_unsloth.sh &
CUDA_VISIBLE_DEVICES=3 LEARNING_RATE=2e-5 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="false" ./super_run_unsloth.sh &
wait

export MODEL="Llama3.2-1B"
export BATCH_SIZE=64
CUDA_VISIBLE_DEVICES=0 LEARNING_RATE=2e-4 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="true" ./super_run_unsloth.sh &
CUDA_VISIBLE_DEVICES=1 LEARNING_RATE=2e-4 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="false" ./super_run_unsloth.sh &
CUDA_VISIBLE_DEVICES=2 LEARNING_RATE=1e-4 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="true" ./super_run_unsloth.sh &
CUDA_VISIBLE_DEVICES=3 LEARNING_RATE=1e-4 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="false" ./super_run_unsloth.sh &
wait
CUDA_VISIBLE_DEVICES=0 LEARNING_RATE=4e-5 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="true" ./super_run_unsloth.sh &
CUDA_VISIBLE_DEVICES=1 LEARNING_RATE=4e-5 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="false" ./super_run_unsloth.sh &
CUDA_VISIBLE_DEVICES=2 LEARNING_RATE=2e-5 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="true" ./super_run_unsloth.sh &
CUDA_VISIBLE_DEVICES=3 LEARNING_RATE=2e-5 RUN_TAG="lr${LEARNING_RATE}" ENABLE_QAT="false" ./super_run_unsloth.sh &
wait
